### ISSUE TITLE
two main sections are uneven

### ISSUE THREAD

**Issue by jayco01** [divforscript/Tip-calculator#6]
Hey, just wanted to say your solution is really good! The calculator works smoothly and your code is clean and easy to follow.

One thing I noticed on desktop is that the two main sections, `costumize-wrapper` and `calculator-wrapper`, aren’t the same width. I’m not sure if you meant for them to be uneven, but if you want them to look even, you can add `flex: 1` to both sections in your ***desktop media query.*** 

For example:

```css
#costumize-wrapper {
    flex: 1;
}

#calculator-wrapper {
    flex: 1;
    display: flex; /* if you need inner content to be flex */
}
```

Just add this inside your desktop (`@media`) CSS. It’ll make both sections expand and fill the available space evenly, which gives the layout a more balanced look.
